package javachatclientgui;

import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;

/**
 * 
 * 
 * @author Michael White (WHTMIC023)
 */
public class ReceiveFileDialog extends javax.swing.JDialog {

    /**
     * Creates new form ReceiveFileDialog
     */
    public ReceiveFileDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    /**
     * Creates new form ReceiveFileDialog with the specified attribute values
     */
    public ReceiveFileDialog(java.awt.Frame parent, boolean modal, String senderAlias, String filename, int filesize) {
        super(parent, modal);
        initComponents();
        this.senderAlias.setText(senderAlias);
        this.filename.setText(filename);
        this.filesize.setText(Integer.toString(filesize));
        this.downloadPath.setText("./downloads/" + filename);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        downloadPath = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        AcceptBtn = new javax.swing.JButton();
        DeclineBtn = new javax.swing.JButton();
        Title = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        senderAlias = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        filename = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        filesize = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        downloadPath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downloadPathActionPerformed(evt);
            }
        });

        jLabel8.setText("Download to:");

        AcceptBtn.setText("Accept");
        AcceptBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcceptBtnActionPerformed(evt);
            }
        });

        DeclineBtn.setText("Decline");
        DeclineBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeclineBtnActionPerformed(evt);
            }
        });

        Title.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        Title.setText("File Transfer Request");

        jLabel2.setText("From:");

        senderAlias.setText("<alias of sender>");

        jLabel4.setText("Filename:");

        filename.setText("<name of file>");

        jLabel6.setText("Size (bytes):");

        filesize.setText("<size of file in bytes>");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(downloadPath)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(Title)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(56, 56, 56)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(filename)
                                    .addComponent(filesize)
                                    .addComponent(senderAlias)))
                            .addComponent(jLabel8))
                        .addGap(0, 98, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(DeclineBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AcceptBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Title)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(senderAlias))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(filename))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(filesize))
                .addGap(30, 30, 30)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(downloadPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AcceptBtn)
                    .addComponent(DeclineBtn))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void downloadPathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downloadPathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_downloadPathActionPerformed

    private void AcceptBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcceptBtnActionPerformed
        String path = downloadPath.getText();
        if (!path.equals("")) {
            try {
                FileOutputStream f = new FileOutputStream(new File(path));
                System.out.println("Sending file accept message");
                JavaChatClientGUI.fileOutputStream.writeUTF("<accept>");
                System.out.println("Receiving file and writing to file");


                byte[] buffer = new byte[4096];
                int count;
                int cumulative = 0;
                while ((count = JavaChatClientGUI.fileInputStream.read(buffer)) > 0) {
                    f.write(buffer, 0, count);
                    cumulative += count;
                    if (cumulative == Integer.parseInt(filesize.getText()))
                        break;
                }
                System.out.println("File write finished.");
                f.close();
                System.out.println("File closed");
            }
            catch (IOException e) {
                System.out.println("Invalid filepath");
                return;
            }
        }
        this.dispose();
    }//GEN-LAST:event_AcceptBtnActionPerformed

    private void DeclineBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeclineBtnActionPerformed
        try {
            JavaChatClientGUI.fileOutputStream.writeUTF("<decline>");
        }
        catch (IOException e) {
            return;
        }
        this.dispose();
    }//GEN-LAST:event_DeclineBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReceiveFileDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReceiveFileDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReceiveFileDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReceiveFileDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ReceiveFileDialog dialog = new ReceiveFileDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AcceptBtn;
    private javax.swing.JButton DeclineBtn;
    private javax.swing.JLabel Title;
    private javax.swing.JTextField downloadPath;
    private javax.swing.JLabel filename;
    private javax.swing.JLabel filesize;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel senderAlias;
    // End of variables declaration//GEN-END:variables
}
